spring-projects/spring-shell

src/main/java/org/springframework/shell/core/SimpleExecutionStrategy.java, src/test/java/org/springframework/shell/core/SimpleExecutionStrategyTest.java
SimpleExecutionStrategy now makes sure the method to be invoked is accessible.
=> SHL-189 - Command classes can now be package protected.

src/main/java/org/springframework/shell/core/JLineShell.java
Fix for cursor reset instead of restore bug that was introduced in jline2 upgrade
=> SHL-146 Restore cursor position on flash

.gitattributes
@ericbottard minor update to help users that checkout the project in Windows platforms - helps mainly with the tests in the spring-shell-standard-commands project
=> add .gitattributes to force *.txt files to use eol=lf at checkout

spring-shell-core/src/main/java/org/springframework/shell/MethodTarget.java, spring-shell-standard-commands/src/main/java/org/springframework/shell/standard/commands/Help.java, spring-shell-standard-commands/src/test/java/org/springframework/shell/standard/commands/HelpTest.java, spring-shell-standard-commands/src/test/resources/org/springframework/shell/standard/commands/HelpTest-testCommandList.txt, spring-shell-standard/src/main/java/org/springframework/shell/standard/ShellMethod.java, spring-shell-standard/src/main/java/org/springframework/shell/standard/StandardMethodTargetRegistrar.java
The output of `help` command is now grouped. Commands without group are in a group called "Default" on top.
Resolves #135
=> Add optional command grouping

spring-shell-docs/src/main/asciidoc/using-spring-shell.adoc
Somehow `@ShellCommand` found its way into the snippets. This commit
replaces it with the correct annotation `@ShellMethod`.
Keep up the good work!
PS: I stumbled upon this typo while writing "First hand experience migrating from Spring Shell 1.2 to 2.0" -  https://devops.datenkollektiv.de/migrating-from-spring-shell-12-to-20.html today.
=> Fix method annotation in some reference documentation snippets

mvnw, mvnw.cmd, pom.xml, spring-shell-docs/pom.xml, spring-shell-table/pom.xml
This commit updates URLs to prefer the https protocol. Redirects are not followed to avoid accidentally expanding intentionally shortened URLs (i.e. if using a URL shortener).
These URLs were unable to be fixed. Please review them to see if they can be manually resolved.
* http://jcommander.org/apidocs/ (200) migrated to:  
http://jcommander.org/apidocs/ ([https](https://jcommander.org/apidocs/) result SSLHandshakeException).
These URLs were fixed successfully.
* http://docs.spring.io/spring-framework/docs/current/javadoc-api/ migrated to:  
https://docs.spring.io/spring-framework/docs/current/javadoc-api/ ([https](https://docs.spring.io/spring-framework/docs/current/javadoc-api/) result 200).
* http://www.apache.org/licenses/LICENSE-2.0 migrated to: …
=> URL Cleanup

pom.xml, spring-shell-core/src/main/java/org/springframework/shell/ApplicationRunnerAutoConfiguration.java, spring-shell-core/src/main/java/org/springframework/shell/CommandRegistryAutoConfiguration.java, spring-shell-core/src/main/java/org/springframework/shell/CompleterAutoConfiguration.java, spring-shell-core/src/main/java/org/springframework/shell/JLineAutoConfiguration.java, spring-shell-core/src/main/java/org/springframework/shell/LineReaderAutoConfiguration.java, spring-shell-core/src/main/java/org/springframework/shell/Shell.java, spring-shell-core/src/main/java/org/springframework/shell/SpringShellAutoConfiguration.java, spring-shell-core/src/main/java/org/springframework/shell/jline/JLineShellAutoConfiguration.java, spring-shell-core/src/main/java/org/springframework/shell/result/IterableResultHandler.java, spring-shell-core/src/main/java/org/springframework/shell/result/ResultHandlerConfig.java, spring-shell-core/src/main/resources/META-INF/spring.factories, spring-shell-core/src/test/java/org/springframework/shell/ShellTest.java, spring-shell-samples/src/main/java/org/springframework/shell/samples/standard/Commands.java, spring-shell-samples/src/main/resources/application.yml, spring-shell-standard-commands/src/main/java/org/springframework/shell/standard/commands/Help.java, spring-shell-standard-commands/src/main/java/org/springframework/shell/standard/commands/Script.java, spring-shell-standard-commands/src/main/java/org/springframework/shell/standard/commands/StandardCommandsAutoConfiguration.java, spring-shell-test-samples/src/test/java/com/example/test/integration/CalculatorCommandsIntegrationTest.java
- Shuffle things around into different auto-config and configuration
classes and use other tricks like ObjectProvider to work around
boot 2.6.x imposing bean cycle checks.
- This is first set of changes to work around this issue, not
to make things perfect. Further refactoring work is needed
making code base more boot 2.x friendly as things are based
on boot 1.5.x times.
- Fixes #324
=> Remove bean cycles

spring-shell-autoconfigure/src/main/java/org/springframework/shell/boot/CommandRegistryAutoConfiguration.java, spring-shell-autoconfigure/src/main/java/org/springframework/shell/boot/ShellContextAutoConfiguration.java, spring-shell-autoconfigure/src/main/java/org/springframework/shell/boot/ShellRunnerAutoConfiguration.java, spring-shell-autoconfigure/src/main/resources/META-INF/spring.factories, spring-shell-core/src/main/java/org/springframework/shell/ConfigurableCommandRegistry.java, spring-shell-core/src/main/java/org/springframework/shell/MethodTarget.java, spring-shell-core/src/main/java/org/springframework/shell/context/DefaultShellContext.java, spring-shell-core/src/main/java/org/springframework/shell/context/InteractionMode.java, spring-shell-core/src/main/java/org/springframework/shell/context/ShellContext.java, spring-shell-core/src/main/java/org/springframework/shell/jline/InteractiveShellRunner.java, spring-shell-core/src/main/java/org/springframework/shell/jline/NonInteractiveShellRunner.java, spring-shell-core/src/test/java/org/springframework/shell/ConfigurableCommandRegistryTest.java, spring-shell-standard-commands/src/main/java/org/springframework/shell/standard/commands/Clear.java, spring-shell-standard-commands/src/main/java/org/springframework/shell/standard/commands/Quit.java, spring-shell-standard-commands/src/main/java/org/springframework/shell/standard/commands/Stacktrace.java, spring-shell-standard/src/main/java/org/springframework/shell/standard/ShellMethod.java, spring-shell-standard/src/main/java/org/springframework/shell/standard/StandardMethodTargetRegistrar.java, spring-shell-standard/src/test/java/org/springframework/shell/standard/StandardMethodTargetRegistrarTest.java, spring-shell-standard/src/test/java/org/springframework/shell/standard/completion/AbstractCompletionsTests.java, spring-shell-standard/src/test/java/org/springframework/shell/standard/completion/BashCompletionsTests.java, spring-shell-test-samples/src/test/java/com/example/test/functional/CalculatorCommandsTest.java
- Add new ShellContext concept which now is just a way
to stash info about interaction mode where ShellRunner
can update supported mode.
- ShellMethod has a new field interactionMode which user
can use to define commands between interactive/non-interactive
modes which then prevents CommandRegistry to show
commands at runtime.
- Fixes #345
=> Separate interactive and non-interactive commands

spring-shell-autoconfigure/src/main/java/org/springframework/shell/boot/ApplicationRunnerAutoConfiguration.java, spring-shell-autoconfigure/src/main/java/org/springframework/shell/boot/NonInteractiveShellRunnerCustomizer.java, spring-shell-autoconfigure/src/main/java/org/springframework/shell/boot/ShellRunnerAutoConfiguration.java, spring-shell-autoconfigure/src/test/java/org/springframework/shell/boot/ShellRunnerAutoConfigurationTests.java, spring-shell-core/src/main/java/org/springframework/shell/DefaultApplicationRunner.java, spring-shell-core/src/main/java/org/springframework/shell/DefaultShellApplicationRunner.java, spring-shell-core/src/main/java/org/springframework/shell/jline/InteractiveShellRunner.java, spring-shell-core/src/main/java/org/springframework/shell/jline/NonInteractiveShellRunner.java, spring-shell-core/src/main/java/org/springframework/shell/jline/ScriptShellRunner.java
- Add ordering on the ApplicationShellRunner which is different than the order on the DefaultApplicationRunner. The latter is order that the default runner will execute wrt other application runners. However, the shell runner order is the order that the default app runner will consider them for "1st available to handle the shell".
- Refactored the shell runners javadocs to clearly spell out the above and make them consistent w/ the new mechanism (not the enabled property of days old). 
- Added customizer which allows us to replace the skipper InteractiveApplicationRunner w/ a customizer that simply filters out the non-command args from the `ApplicationArguments` (@jvalkeal )
~This is WIP as I have not added any unit/int testing. I have manually verified the interactive and non-interactive …
=> Add non-interactive shell runner customizer

spring-shell-autoconfigure/src/main/java/org/springframework/shell/boot/SpringShellProperties.java, spring-shell-autoconfigure/src/main/java/org/springframework/shell/boot/StandardCommandsAutoConfiguration.java, spring-shell-autoconfigure/src/test/java/org/springframework/shell/boot/SpringShellPropertiesTests.java, spring-shell-autoconfigure/src/test/java/org/springframework/shell/boot/StandardCommandsAutoConfigurationTests.java, spring-shell-standard-commands/src/main/java/org/springframework/shell/standard/commands/Help.java
- New option spring.shell.command.help.grouping-mode which can be either flat/group.
- Build-in help command can now choose if to group command or just show flat list.
- Fixes #347
=> Make grouping configurable in build-in help

pom.xml, spring-shell-core/pom.xml, spring-shell-core/src/main/java/org/springframework/shell/component/MultiItemSelector.java, spring-shell-core/src/main/java/org/springframework/shell/component/PathInput.java, spring-shell-core/src/main/java/org/springframework/shell/component/SingleItemSelector.java, spring-shell-core/src/main/java/org/springframework/shell/component/StringInput.java, spring-shell-core/src/main/java/org/springframework/shell/component/context/BaseComponentContext.java, spring-shell-core/src/main/java/org/springframework/shell/component/context/ComponentContext.java, spring-shell-core/src/main/java/org/springframework/shell/component/support/AbstractComponent.java, spring-shell-core/src/main/java/org/springframework/shell/component/support/AbstractSelectorComponent.java, spring-shell-core/src/main/java/org/springframework/shell/component/support/AbstractTextComponent.java, spring-shell-core/src/main/java/org/springframework/shell/component/support/Enableable.java, spring-shell-core/src/main/java/org/springframework/shell/component/support/Itemable.java, spring-shell-core/src/main/java/org/springframework/shell/component/support/Matchable.java, spring-shell-core/src/main/java/org/springframework/shell/component/support/Nameable.java, spring-shell-core/src/main/java/org/springframework/shell/component/support/SelectorItem.java, spring-shell-core/src/main/resources/org/springframework/shell/component/multi-item-selector-default.stg, spring-shell-core/src/main/resources/org/springframework/shell/component/path-input-default.stg, spring-shell-core/src/main/resources/org/springframework/shell/component/single-item-selector-default.stg, spring-shell-core/src/main/resources/org/springframework/shell/component/string-input-default.stg, spring-shell-core/src/test/java/org/springframework/shell/component/AbstractShellTests.java, spring-shell-core/src/test/java/org/springframework/shell/component/MultiItemSelectorTests.java, spring-shell-core/src/test/java/org/springframework/shell/component/PathInputTests.java, spring-shell-core/src/test/java/org/springframework/shell/component/ShellAssertions.java, spring-shell-core/src/test/java/org/springframework/shell/component/SingleItemSelectorTests.java, spring-shell-core/src/test/java/org/springframework/shell/component/StringInputTests.java, spring-shell-core/src/test/java/org/springframework/shell/component/context/ComponentContextTests.java, spring-shell-samples/src/main/java/org/springframework/shell/samples/standard/ComponentCommands.java
- Add first preliminary model of building and working with
higher level components.
- Components for text input, path input, single selector and
multi selector.
- Components renderings are based on ANTLR ST templates while
there is support for building rendering output manually.
- Add these into sample.
- This is a base of additional work what goes to these components
and concepts around it.
- Relates #360
=> Basic UI components

spring-shell-core/src/main/java/org/springframework/shell/component/ConfirmationInput.java, spring-shell-core/src/main/resources/META-INF/native-image/resource-config.json, spring-shell-core/src/main/resources/org/springframework/shell/component/confirmation-input-default.stg, spring-shell-core/src/test/java/org/springframework/shell/component/ConfirmationInputTests.java, spring-shell-samples/src/main/java/org/springframework/shell/samples/standard/ComponentCommands.java
- New ConfirmationInput component
- Add missing native resource config for templates.
- Add sample "component confirmation", use flag --no
to switch default from yes to no.
- Fixes #366
=> Add confirmation component

spring-shell-core/src/main/java/org/springframework/shell/style/TemplateExecutor.java, spring-shell-standard-commands/src/main/java/org/springframework/shell/standard/commands/Version.java
- Now passing version command attributes
even if those are nulls(not set) as ST
logs those in a listener as errors while
it doesn't cause any failures.
- Change all LoggingSTErrorListener methods
into debug level to limit more noise.
- Fixes #363
=> Fix version command attributes

spring-shell-autoconfigure/src/main/java/org/springframework/shell/boot/ThemingAutoConfiguration.java, spring-shell-core/src/main/java/org/springframework/shell/ShellRunner.java, spring-shell-core/src/main/java/org/springframework/shell/jline/NonInteractiveShellRunner.java, spring-shell-core/src/main/java/org/springframework/shell/jline/ScriptShellRunner.java
Also:
* Rename ThemeResolver bean to avoid clash w/ Spring Boot registered ThemeResolver
* Move shell runner precedence to public static field to allow extension/access
This was needed to support `spring.shell.commandFile` option in SCDF shell. I originally implemented it in SCDF by creating a separate NonInteractiveShellRunner. However, its cleaner to simply support N commands here and let the `commandfile->commands` come in via customizer in SCDF (see [here](https://github.com/spring-cloud/spring-cloud-dataflow/pull/4835/files#diff-7c1674166952308591746a47ec386ac05f55151228991c818a825dfe74b59e07R74)).
=> Add support for multiple non-interactive commands

spring-shell-core/src/main/java/org/springframework/shell/CommandRegistry.java, spring-shell-core/src/main/java/org/springframework/shell/ConfigurableCommandRegistry.java, spring-shell-core/src/main/java/org/springframework/shell/MethodTarget.java, spring-shell-core/src/main/java/org/springframework/shell/Shell.java, spring-shell-core/src/test/java/org/springframework/shell/ShellTest.java, spring-shell-samples/src/main/java/org/springframework/shell/samples/standard/RegisterCommands.java, spring-shell-standard-commands/src/test/java/org/springframework/shell/standard/commands/HelpTest.java
- Extend CommandRegistry for add/remove methods.
- For rest of shell classes move to use registry
directly instead of caching commands as registry
is not immutable anymore.
- Add new sample
- Fixes #379
=> Add dynamic command registration

spring-shell-autoconfigure/src/main/java/org/springframework/shell/boot/ComponentFlowAutoConfiguration.java, spring-shell-autoconfigure/src/main/java/org/springframework/shell/boot/ComponentFlowCustomizer.java, spring-shell-autoconfigure/src/main/resources/META-INF/spring.factories, spring-shell-core/src/main/java/org/springframework/shell/component/flow/ComponentFlow.java, spring-shell-core/src/test/java/org/springframework/shell/component/flow/ComponentFlowTests.java, spring-shell-samples/src/main/java/org/springframework/shell/samples/standard/ComponentFlowCommands.java
- ComponentFlowAutoConfiguration which creates a builder bean
and configures ComponentFlowCustomizer to set needed
defaults for terminal, resource loader and template executor.
- Fixes #387
=> Add auto-config for ComponentFlow

.github/workflows/e2e.yml, e2e/spring-shell-e2e-tests/.gitignore, e2e/spring-shell-e2e-tests/.prettierignore, e2e/spring-shell-e2e-tests/.prettierrc.json, e2e/spring-shell-e2e-tests/jest.config.js, e2e/spring-shell-e2e-tests/package-lock.json, e2e/spring-shell-e2e-tests/package.json, e2e/spring-shell-e2e-tests/src/utils.ts, e2e/spring-shell-e2e-tests/test/builtin.test.ts, e2e/spring-shell-e2e-tests/test/flow.test.ts, e2e/spring-shell-e2e-tests/tsconfig.json, e2e/spring-shell-e2e/.gitignore, e2e/spring-shell-e2e/.prettierrc.json, e2e/spring-shell-e2e/package-lock.json, e2e/spring-shell-e2e/package.json, e2e/spring-shell-e2e/src/cli.ts, e2e/spring-shell-e2e/tsconfig.json
- Add node code for e2e tests. This is a first take to try running
these tests via actions.
- Relates to #401
=> Initial attempt for e2e tests

spring-shell-core/src/main/java/org/springframework/shell/command/CommandParser.java, spring-shell-core/src/test/java/org/springframework/shell/command/CommandExecutionTests.java, spring-shell-standard/src/main/java/org/springframework/shell/standard/StandardMethodTargetRegistrar.java, spring-shell-standard/src/test/java/org/springframework/shell/standard/StandardMethodTargetRegistrarTests.java
- Change parsing to extract and use option default value
and also hook it with @ShellOption.
- Fixes #409
=> Fix use of default values

spring-shell-core/src/main/java/org/springframework/shell/component/flow/BaseSingleItemSelector.java, spring-shell-core/src/main/java/org/springframework/shell/component/flow/ComponentFlow.java, spring-shell-core/src/main/java/org/springframework/shell/component/flow/SingleItemSelectorSpec.java, spring-shell-core/src/main/java/org/springframework/shell/component/support/AbstractSelectorComponent.java, spring-shell-core/src/test/java/org/springframework/shell/component/flow/ComponentFlowTests.java, spring-shell-samples/src/main/java/org/springframework/shell/samples/standard/ComponentFlowCommands.java
- Tweak flow framework so that single item selector
can be configured with a default item which is then
"exposed" automatically so that user can just hit enter.
- Fixes #414
=> Expose default option in SingleItemSelector

spring-shell-autoconfigure/src/main/java/org/springframework/shell/boot/JLineAutoConfiguration.java, spring-shell-autoconfigure/src/main/java/org/springframework/shell/boot/LineReaderAutoConfiguration.java, spring-shell-autoconfigure/src/main/java/org/springframework/shell/boot/SpringShellProperties.java, spring-shell-autoconfigure/src/main/java/org/springframework/shell/boot/UserConfigAutoConfiguration.java, spring-shell-autoconfigure/src/main/resources/META-INF/spring.factories, spring-shell-autoconfigure/src/test/java/org/springframework/shell/boot/LineReaderAutoConfigurationTests.java, spring-shell-autoconfigure/src/test/java/org/springframework/shell/boot/SpringShellPropertiesTests.java, spring-shell-autoconfigure/src/test/java/org/springframework/shell/boot/UserConfigAutoConfigurationTests.java, spring-shell-core/src/main/java/org/springframework/shell/config/UserConfigPathProvider.java, spring-shell-samples/src/main/resources/application.yml
- UserConfigPathProvider interface to provid "user-level"
config directory which can be used within a shell.
- New options which can be used to configure behaviour.
spring.shell.history.enabled
spring.shell.history.name
spring.shell.config.location
spring.shell.config.env
- Fixes #417
=> Make history file path configurable

spring-shell-core/src/main/java/org/springframework/shell/result/ResultHandlerConfig.java, spring-shell-core/src/main/java/org/springframework/shell/result/ThrowableResultHandler.java
- Change how errors are printed for interactive
vs non-interactive mode.
- This now changes behaviour so that stacktrace is printed
if non-interactive mode is active so that user has a change
to see the full error.
- Fixes #427
=> Better errors with non-interactive mode

.vscode/launch.json, e2e/spring-shell-e2e-tests/test/sample-e2e-exit-code.test.ts, spring-shell-autoconfigure/src/main/java/org/springframework/shell/boot/ExitCodeAutoConfiguration.java, spring-shell-autoconfigure/src/main/java/org/springframework/shell/boot/SpringShellAutoConfiguration.java, spring-shell-autoconfigure/src/main/resources/META-INF/spring.factories, spring-shell-core/src/main/java/org/springframework/shell/Shell.java, spring-shell-core/src/main/java/org/springframework/shell/command/CommandExitCode.java, spring-shell-core/src/main/java/org/springframework/shell/command/CommandRegistration.java, spring-shell-core/src/main/java/org/springframework/shell/exit/ExitCodeMappings.java, spring-shell-core/src/test/java/org/springframework/shell/ShellTests.java, spring-shell-core/src/test/java/org/springframework/shell/command/CommandRegistrationTests.java, spring-shell-docs/src/main/asciidoc/using-shell-commands-exitcode.adoc, spring-shell-docs/src/main/asciidoc/using-shell-commands.adoc, spring-shell-docs/src/test/java/org/springframework/shell/docs/ExitCodeSnippets.java, spring-shell-samples/src/main/java/org/springframework/shell/samples/standard/E2ECommands.java, spring-shell-standard-commands/src/main/java/org/springframework/shell/standard/commands/Script.java
- New configurations to CommandRegistration
- Re-using exit code concepts from boot
- Handling exit codes only in non-interactive mode
- Adding e2e commands and tests for better coverage
- Fixes #431
=> Add support for exit codes

spring-shell-core/src/main/java/org/springframework/shell/jline/InteractiveShellRunner.java, spring-shell-core/src/test/java/org/springframework/shell/jline/InteractiveShellRunnerTests.java
- support capturing CTRL+D to exit the shell
- add some tests for CTRL+C, CTRL+D cases
=> Capturing CTRL+D (EOF) to exit the shell

spring-shell-autoconfigure/src/main/java/org/springframework/shell/boot/SpringShellProperties.java, spring-shell-autoconfigure/src/main/java/org/springframework/shell/boot/ThemingAutoConfiguration.java, spring-shell-autoconfigure/src/test/java/org/springframework/shell/boot/SpringShellPropertiesTests.java, spring-shell-autoconfigure/src/test/java/org/springframework/shell/boot/ThemingAutoConfigurationTests.java, spring-shell-core/src/main/java/org/springframework/shell/style/FigureSettings.java, spring-shell-core/src/main/java/org/springframework/shell/style/StringToStyleExpressionRenderer.java, spring-shell-core/src/main/java/org/springframework/shell/style/StyleSettings.java, spring-shell-core/src/main/java/org/springframework/shell/style/TemplateExecutor.java, spring-shell-core/src/main/java/org/springframework/shell/style/ThemeActive.java, spring-shell-core/src/main/java/org/springframework/shell/style/ThemeResolver.java, spring-shell-core/src/main/java/org/springframework/shell/style/ThemeSettings.java, spring-shell-core/src/main/resources/org/springframework/shell/component/confirmation-input-default.stg, spring-shell-core/src/main/resources/org/springframework/shell/component/multi-item-selector-default.stg, spring-shell-core/src/main/resources/org/springframework/shell/component/path-input-default.stg, spring-shell-core/src/main/resources/org/springframework/shell/component/single-item-selector-default.stg, spring-shell-core/src/main/resources/org/springframework/shell/component/string-input-default.stg, spring-shell-core/src/test/java/org/springframework/shell/component/AbstractShellTests.java, spring-shell-core/src/test/java/org/springframework/shell/component/MultiItemSelectorTests.java, spring-shell-core/src/test/java/org/springframework/shell/component/flow/AbstractShellTests.java, spring-shell-core/src/test/java/org/springframework/shell/style/TemplateExecutorTests.java, spring-shell-core/src/test/java/org/springframework/shell/style/ThemeResolverTests.java, spring-shell-core/src/test/java/org/springframework/shell/style/ThemeSettingsTests.java, spring-shell-samples/src/main/java/org/springframework/shell/samples/standard/StyleCommands.java, spring-shell-standard-commands/src/main/resources/template/help-command-default.stg, spring-shell-standard-commands/src/main/resources/template/help-commands-default.stg, spring-shell-standard-commands/src/test/java/org/springframework/shell/standard/commands/HelpTests.java
- Add theme settings for figures.
- Settings for styles are now in it own class and
ThemeSettings are wrapping those.
- Prefixed formatting string to have `style-` prefix.
- Templates can now use added `figures` dictionary which
is resolved per activated theme.
- Create `dump` theme.
- New `ThemeActive` interface where default impl uses dump
theme if `CI` or `NO_COLOR` env is set.
- Rework existing templates.
- Fixes #442
=> Rework themes support

spring-shell-core/src/main/java/org/springframework/shell/command/CommandExecution.java, spring-shell-core/src/main/java/org/springframework/shell/component/ConfirmationInput.java, spring-shell-core/src/main/java/org/springframework/shell/component/MultiItemSelector.java, spring-shell-core/src/main/java/org/springframework/shell/component/PathInput.java, spring-shell-core/src/main/java/org/springframework/shell/component/SingleItemSelector.java, spring-shell-core/src/main/java/org/springframework/shell/component/StringInput.java, spring-shell-core/src/main/java/org/springframework/shell/component/context/ComponentContext.java, spring-shell-core/src/main/java/org/springframework/shell/component/support/AbstractComponent.java, spring-shell-core/src/main/java/org/springframework/shell/component/support/AbstractSelectorComponent.java, spring-shell-core/src/main/java/org/springframework/shell/component/support/AbstractTextComponent.java, spring-shell-core/src/test/java/org/springframework/shell/component/AbstractShellTests.java, spring-shell-core/src/test/java/org/springframework/shell/component/ConfirmationInputTests.java, spring-shell-core/src/test/java/org/springframework/shell/component/MultiItemSelectorTests.java, spring-shell-core/src/test/java/org/springframework/shell/component/PathInputTests.java, spring-shell-core/src/test/java/org/springframework/shell/component/SingleItemSelectorTests.java, spring-shell-core/src/test/java/org/springframework/shell/component/StringInputTests.java, spring-shell-core/src/test/java/org/springframework/shell/component/flow/AbstractShellTests.java, spring-shell-samples/src/main/java/org/springframework/shell/samples/standard/ComponentFlowCommands.java
- Adding a concept of no-tty which in this commit simply
tracks DumbTerminal as jline creates that if there nothing
better.
- For components without tty don't go to interaction loop.
- For new sample show that we can at least manually handle
required option with a flow while command option is not
required.
- Fixes #444
=> Components can't use interactive mode without tty

spring-shell-samples/src/main/java/org/springframework/shell/samples/standard/AliasCommands.java, spring-shell-standard-commands/src/main/java/org/springframework/shell/standard/commands/CommandInfoModel.java, spring-shell-standard-commands/src/main/java/org/springframework/shell/standard/commands/GroupsInfoModel.java, spring-shell-standard-commands/src/main/resources/template/help-command-default.stg, spring-shell-standard-commands/src/main/resources/template/help-commands-default.stg, spring-shell-standard-commands/src/test/java/org/springframework/shell/standard/commands/CommandAvailabilityInfoModelTests.java, spring-shell-standard-commands/src/test/java/org/springframework/shell/standard/commands/CommandInfoModelTests.java, spring-shell-standard-commands/src/test/java/org/springframework/shell/standard/commands/GroupsInfoModelTests.java, spring-shell-standard-commands/src/test/resources/org/springframework/shell/standard/commands/HelpTests-testCommandListDefault.txt, spring-shell-standard-commands/src/test/resources/org/springframework/shell/standard/commands/HelpTests-testCommandListFlat.txt
- Add info about aliases into model structure used by help
command templating.
- Add some tests to models.
- Change help commands list to group command and its aliases together.
- Change help command to show aliases.
- Fixes #458
- Fixes #426
=> Fix alias usage in help command

e2e/spring-shell-e2e-tests/test/sample-e2e-default-value.test.ts, spring-shell-samples/src/main/java/org/springframework/shell/samples/e2e/DefaultValueCommands.java, spring-shell-standard/src/main/java/org/springframework/shell/standard/StandardMethodTargetRegistrar.java, spring-shell-standard/src/test/java/org/springframework/shell/standard/StandardMethodTargetRegistrarTests.java
- In a case where arg is given as boolean and with plain
@ShellOption (user doesn't define defaults), configure
arg not to be mandatory and with default value false.
- This brings this spesific case more close how it behave
in older shell version.
- Having `@ShellOption boolean arg1` it now works as:
my-shell:>e2e reg default-value-boolean3
Hello false
my-shell:>e2e reg default-value-boolean3 --arg1
Hello true
my-shell:>e2e reg default-value-boolean3 --arg1 false
Hello false
my-shell:>e2e reg default-value-boolean3 --arg1 true
Hello true
- Fixes #461
=> Default boolean arg to false

spring-shell-core/src/main/java/org/springframework/shell/Shell.java, spring-shell-core/src/main/java/org/springframework/shell/completion/RegistrationOptionsCompletionResolver.java, spring-shell-core/src/test/java/org/springframework/shell/ShellTests.java, spring-shell-core/src/test/java/org/springframework/shell/completion/RegistrationOptionsCompletionResolverTests.java, spring-shell-samples/src/main/java/org/springframework/shell/samples/e2e/InteractiveCompletionCommands.java
- This commit fixes two issues.
- Firstly complete with correct option as existing bug was
to wrongly always complete with first option which used
wrong provider.
- Secondly filter out duplicate option proposals giving better
result when options is already in place.
- Fixes #495
=> Apply correct completion

spring-shell-core/src/main/java/org/springframework/shell/component/MultiItemSelector.java, spring-shell-core/src/main/java/org/springframework/shell/component/SingleItemSelector.java, spring-shell-core/src/main/java/org/springframework/shell/component/context/BaseComponentContext.java, spring-shell-core/src/main/java/org/springframework/shell/component/context/ComponentContext.java, spring-shell-core/src/main/java/org/springframework/shell/style/StringToStyleExpressionRenderer.java, spring-shell-core/src/main/resources/org/springframework/shell/component/multi-item-selector-default.stg, spring-shell-core/src/main/resources/org/springframework/shell/component/single-item-selector-default.stg, spring-shell-core/src/test/java/org/springframework/shell/component/AbstractShellTests.java, spring-shell-core/src/test/java/org/springframework/shell/style/StringToStyleExpressionRendererTests.java, spring-shell-docs/src/main/asciidoc/using-shell-components-ui-render.adoc, spring-shell-samples/src/main/java/org/springframework/shell/samples/standard/ComponentCommands.java
- BaseComponentContext has new field terminalWidth.
- StringToStyleExpressionRenderer contains new format for "truncate-" prefixes and this is something what template can use to instruct max length based on terminal width.
- Change single/multi selectors to use this feature.
- Fixes #543
=> Component text can be truncated

.github/workflows/release-ga.yml, .github/workflows/release-milestone.yml
Signed-off-by: jongwooo <jongwooo.han@gmail.com>
Resolve  #657 
Update workflows to use environment file instead of deprecated `set-output` command. 
For more information, see: [https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)
I found the workflow files that use `set-output` command through the following command:
```bash
$ find .github/workflows -name '*.yml' | xargs egrep '\bset-output\b'
```
**AS-IS**
```yml
run: |
echo "::set-output name=project-version::$PROJECT_VERSION"
```
**TO-BE**
```yml
run: |
echo "project-version=$PROJECT_VERSION" >> $GITHUB_OUTPUT
```
=> Replace deprecated command with environment file

spring-shell-core/src/main/java/org/springframework/shell/component/StringInput.java, spring-shell-core/src/main/java/org/springframework/shell/component/flow/ComponentFlow.java, spring-shell-core/src/test/java/org/springframework/shell/component/StringInputTests.java, spring-shell-docs/src/test/java/org/springframework/shell/docs/UiComponentSnippets.java, spring-shell-samples/src/main/java/org/springframework/shell/samples/standard/ComponentCommands.java
Currently, spring-shell-core/src/main/java/org/springframework/shell/component/StringInput.java contains the former, which is likely a typographical error? Resolves #686
=> Rename setMaskCharater to setMaskCharacter

spring-shell-autoconfigure/src/main/java/org/springframework/shell/boot/CommandCatalogAutoConfiguration.java, spring-shell-autoconfigure/src/test/java/org/springframework/shell/boot/CommandCatalogAutoConfigurationTests.java
A Small Bugfix. The `ShellContext` is not passed to `CommandCatalog.of` in `CommandCatalogAutoConfiguration`. As a consequence, command filtering by interaction mode is not working as expected.
=> Pass ShellContext to CommandCatalog.of in CommandCatalogAutoConfig

spring-shell-samples/spring-shell-sample-catalog/spring-shell-sample-catalog.gradle, spring-shell-samples/spring-shell-sample-commands/spring-shell-sample-commands.gradle, spring-shell-samples/spring-shell-sample-e2e/spring-shell-sample-e2e.gradle
Addresses a build issue where the build information being generated on each build includes a timestamp. Since the timestamp is incremented each time, no incremental builds will take place for those that tasks that depend on this `buildInfo` task.
The build scan can be seen here with performance details, with a overall time for executing tasks of 45.650s: 
https://scans.gradle.com/s/vgim65zsvbrzm/performance/execution#wall-clock-time
Without timestamps being put in the build info, the overall time for executing tasks was 14.763 seconds:  
https://scans.gradle.com/s/p5ldndkjxwy4g/performance/execution#wall-clock-time
The spring boot documentation regarding actually mentions this behavior. Following the link below and looking at the example on excluding the 'time' show the essence of this …
=> Do not include timestamp for buildInfo.

spring-shell-autoconfigure/src/main/java/org/springframework/shell/boot/StandardAPIAutoConfiguration.java
add `LazyInitializationExcludeFilter` to fix #902
=> Bugfix: Tab-completion fails

spring-shell-core/src/main/java/org/springframework/shell/DefaultShellApplicationRunner.java, spring-shell-core/src/main/java/org/springframework/shell/ShellRunner.java, spring-shell-core/src/main/java/org/springframework/shell/jline/InteractiveShellRunner.java, spring-shell-core/src/main/java/org/springframework/shell/jline/NonInteractiveShellRunner.java, spring-shell-core/src/main/java/org/springframework/shell/jline/ScriptShellRunner.java, spring-shell-core/src/test/java/org/springframework/shell/jline/InteractiveShellRunnerTests.java, spring-shell-core/src/test/java/org/springframework/shell/jline/NonInteractiveShellRunnerTests.java, spring-shell-core/src/test/java/org/springframework/shell/jline/ScriptShellRunnerTests.java, spring-shell-test/src/main/java/org/springframework/shell/test/ShellTestClient.java
- In ShellRunner interface replace use of boot's ApplicationArguments into plain string array.
- Deprecate old methods with some fallbacks to give time for users to do updates.
- NonInteractiveShellRunner contains one breaking change due to its public api to set function doing conversion from ApplicationArguments which was potentially used via customizer hooks.
- Deprecations planned to get removed in 3.4.x.
- Fixes #1057
=> Use string array in ShellRunner

.github/workflows/e2e.yml, e2e/spring-shell-e2e/package-lock.json, e2e/spring-shell-e2e/package.json
- Bump node-pty from 0.11.0-beta19 to 1.0.0
- Bump xterm-headless from 4.18.0 to 5.5.0
- Rename xterm-headless to @xterm/headless as per https://www.npmjs.com/package/xterm-headless
- Unpin Python 3.11 in e2e test by reverting commit https://github.com/spring-projects/spring-shell/commit/8097f1eb91b6d5bd8e6ff4296e8900d5649a812a because it's no longer necessary as explained in https://github.com/spring-projects/spring-shell/issues/909#issuecomment-2188962147 .
- Fixes https://github.com/spring-projects/spring-shell/issues/909
- Fixes https://github.com/spring-projects/spring-shell/issues/921
=> chore: bump spring-shell-e2e dependencies
